#ifndef HWoWSockets
#define HWoWSockets

#define AUTH_REQUEST 100
#define AUTH_RESPONSE 105
#define LOGOUT_REQUEST 110
#define LOGOUT_RESPONSE 115

#define CHAR_LIST_REQUEST 200
#define CHAR_LIST_RESPONSE 205

#define CHAR_GEAR_REQUEST 210
#define CHAR_GEAR_RESPONSE 215

#define CHAR_INTERACT_TRADE_REQUEST 300
#define CHAR_INTERACT_TRADE_RESPONSE 305
#define CHAR_INTERACT_GROUP_INV_REQUEST 310
#define CHAR_INTERACT_GROUP_INV_RESPONSE 315

#define CHAR_LOG_IN_GAME_REQUEST 400
#define CHAR_LOG_IN_GAME_RESPONSE 405

#define BAG_ITEM_INFO_REQUEST 500
#define BAG_ITEM_INFO_RESPONSE 505
#define BAG_ITEM_USE_REQUEST 510
#define BAG_ITEM_USE_RESPONSE 515
#define BAG_ITEM_MOVE_REQUEST 520
#define BAG_ITEM_MOVE_RESPONSE 525
#define BAG_ITEM_DELETE_REQUEST 530
#define BAG_ITEM_DELETE_RESPONSE 535
#define BAG_ITEM_REPAIR_REQUEST 540
#define BAG_ITEM_REPAIR_RESPONSE 545

#define BAG_ITEMS_LIST_REQUEST 600
#define BAG_ITEMS_LIST_RESPONSE 605

#define ZONE_NPC_LIST_REQUEST 700
#define ZONE_NPC_LIST_RESPONSE 705
#define NPC_INFO_REQUEST 710
#define NPC_INFO_RESPONSE 715
#define NPC_INTERACT_REQUEST 720
#define NPC_INTERACT_RESPONSE 725
#define ZONE_ITEM_LIST_REQUEST 730
#define ZONE_ITEM_LIST_RESPONSE 735
#define ITEM_INFO_REQUEST 740
#define ITEM_INFO_RESPONSE 745
#define ITEM_INTERACT_REQUEST 750
#define ITEM_INTERACT_RESPONSE 755

#define LOOT_LIST_REQUEST 800
#define LOOT_LIST_RESPONSE 805
#define LOOT_ITEM_REQUEST 810
#define LOOT_ITEM_RESPONSE 815

#define CHAT_MSG_REQUEST 900
#define CHAT_MSG_RESPONSE 900



#endif
